function lgraph_out=ReplaceLayer_FP32toBin(lgraph_in)
lgraph_out=lgraph_in;
for i=1:size(lgraph_out.Layers,1)
    if ismethod(lgraph_out.Layers(i,1),'Convolution2DLayer')
        if strcmp(lgraph_out.Layers(i,1).PaddingMode ,'same')
            binconv=Binarizedconvolution2dLayer(lgraph_out.Layers(i,1).FilterSize, ...
                lgraph_out.Layers(i,1).NumFilters, ...
                'Padding',lgraph_out.Layers(i,1).PaddingMode, ...
                'Stride',lgraph_out.Layers(i,1).Stride, ...
                'Name',lgraph_out.Layers(i,1).Name);
        else
            binconv=Binarizedconvolution2dLayer(lgraph_out.Layers(i,1).FilterSize, ...
                lgraph_out.Layers(i,1).NumFilters, ...
                'Padding',lgraph_out.Layers(i,1).PaddingSize, ...
                'Stride',lgraph_out.Layers(i,1).Stride, ...
                'Name',lgraph_out.Layers(i,1).Name);
        end
        binconv.Weights=lgraph_out.Layers(i,1).Weights;
        lgraph_out=replaceLayer(lgraph_out,lgraph_out.Layers(i,1).Name,binconv);
        
    elseif ismethod(lgraph_out.Layers(i,1),'TransposedConvolution2DLayer')
        if strcmp(lgraph_out.Layers(i,1).CroppingMode ,'same')
            binTconv=BinarizedtransposedConv2dLayer(lgraph_out.Layers(i,1).FilterSize, ...
                lgraph_out.Layers(i,1).NumFilters, ...
                'Cropping','same', ..., ...%'same', ... %'CroppingSize',Net.Layers(i,1).CroppingSize, ...
                'Stride',lgraph_out.Layers(i,1).Stride, ...
                'BiasLearnRateFactor',0,...
                'Name',lgraph_out.Layers(i,1).Name);
        else
            binTconv=BinarizedtransposedConv2dLayer(lgraph_out.Layers(i,1).FilterSize, ...
                lgraph_out.Layers(i,1).NumFilters, ...
                'Cropping',lgraph_out.Layers(i,1).CroppingSize, ..., ...%'same', ... %'CroppingSize',Net.Layers(i,1).CroppingSize, ...
                'Stride',lgraph_out.Layers(i,1).Stride, ...
                'BiasLearnRateFactor',0,...
                'Name',lgraph_out.Layers(i,1).Name);
        end
        binTconv.Weights=lgraph_out.Layers(i,1).Weights;
        lgraph_out=replaceLayer(lgraph_out,lgraph_out.Layers(i,1).Name,binTconv);
        
    elseif ismethod(lgraph_out.Layers(i,1),'ReLULayer')
        signact=SignumActivation(lgraph_out.Layers(i,1).Name);
        lgraph_out=replaceLayer(lgraph_out,lgraph_out.Layers(i,1).Name,signact);
    end
end
end