classdef BConvolution2DGPUStrategy < nnet.internal.cnn.layer.util.ExecutionStrategy
    % Convolution2DGPUStrategy   Execution strategy for running the
    % convolution on the GPU
    
    %   Copyright 2016-2018 The MathWorks, Inc.
    
    methods
        function [Z, memory] = forward(~, X, ...
                weights, bias, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                verticalStride, horizontalStride, ...
                verticalDilation, horizontalDilation)
            paddingSize = [topPad bottomPad leftPad rightPad];
            
            weights= sign(weights);  %%%%%%%%%%%%%%%%%%%%%
            weights(weights==0)=1;  %%%%%%%%%%%%%%%%%%%%%
            
            if iPaddingIsSymmetric(paddingSize)
                Z = nnet.internal.cnngpu.convolveForward2D( ...
                    X, weights, ...
                    topPad, leftPad, ...
                    bottomPad, rightPad, ...
                    verticalStride, horizontalStride, ...
                    verticalDilation, horizontalDilation) + bias;
            else
                X = iPadArray(X, paddingSize);
                Z = nnet.internal.cnngpu.convolveForward2D( ...
                    X, weights, ...
                    0, 0, ...
                    0, 0, ...
                    verticalStride, horizontalStride, ...
                    verticalDilation, horizontalDilation) + bias;
            end
            memory = [];
        end
        
        function [dX,dW] = backward(~, ...
                X, weights, dZ, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                strideHeight, strideWidth, ...
                verticalDilation, horizontalDilation)
            paddingSize = [topPad bottomPad leftPad rightPad];
            needsWeightGradients = nargout > 1;
            
            weightsFP=weights;    %%%%%%%%%%%%%%%%%%%%%
            weights= sign(weights);  %%%%%%%%%%%%%%%%%%%%%
            weights(weights==0)=1;  %%%%%%%%%%%%%%%%%%%%%
            
            if iPaddingIsSymmetric(paddingSize)
                dX = nnet.internal.cnngpu.convolveBackwardData2D( ...
                    X, weights, dZ, ...
                    topPad, leftPad, ...
                    bottomPad, rightPad, ...
                    strideHeight, strideWidth, ...
                    verticalDilation, horizontalDilation);
                if needsWeightGradients
                    
                    weights=weightsFP; %%%%%%%%%%%%%%%%%
                    
                    dW{1} = nnet.internal.cnngpu.convolveBackwardFilter2D( ...
                        X, weights, dZ, ...
                        topPad, leftPad, ...
                        bottomPad, rightPad, ...
                        strideHeight, strideWidth, ...
                        verticalDilation, horizontalDilation);
                end
            else
                X = iPadArray(X, paddingSize);
                dX = nnet.internal.cnngpu.convolveBackwardData2D( ...
                    X, weights, dZ, ...
                    0, 0, ...
                    0, 0, ...
                    strideHeight, strideWidth, ...
                    verticalDilation, horizontalDilation);
                dX = iUnpadArray(dX, paddingSize);
                if needsWeightGradients
                    
                    weights=weightsFP; %%%%%%%%%%%%%%%%%
                    
                    dW{1} = nnet.internal.cnngpu.convolveBackwardFilter2D( ...
                        X, weights, dZ, ...
                        0, 0, ...
                        0, 0, ...
                        strideHeight, strideWidth, ...
                        verticalDilation, horizontalDilation);
                end
            end
            if needsWeightGradients
                dW{2} = nnet.internal.cnngpu.convolveBackwardBias2D(dZ);
            end
        end
        
    end
end

function tf = iPaddingIsSymmetric(paddingSize)
tf = nnet.internal.cnn.layer.padding.isPaddingSymmetric(paddingSize);
end

function outputArray = iPadArray(inputArray, paddingSize)
outputArray = nnet.internal.cnn.layer.padding.padArray(inputArray, paddingSize);
end

function outputArray = iUnpadArray(inputArray, paddingSize)
outputArray = nnet.internal.cnn.layer.padding.unpadArray(inputArray, paddingSize);
end
